---
- name: Setup
  hosts: all
  tasks:
  - name: Add Ansible user
    user:
      name: ansible
      state: present
      generate_ssh_key: true
  - name: Ensure that NTP is available
    apt:
      name: ntp
      state: present
  - name: Ensure that NTP service is started
    service:
      name: ntp
      state: started
